config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show]

  get 'about' => 'welcome#about'
  root to: 'welcome#index'
  post :incoming, to: 'incoming#create'

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/bookmark.rb
require "link_thumbnailer"

class Bookmark < ActiveRecord::Base
  after_save :add_thumbnail_and_title

  has_many :likes, dependent: :destroy
  belongs_to :topic
  belongs_to :user 

  private

  def add_thumbnail_and_title
    begin
      puts "Strated generating thumbanil and title"
      obj = LinkThumbnailer.generate(url)
      thumbnail = obj.images.first.src.to_s
      title = self.title || obj.title 
      description = self.description || obj.description
      self.update_columns(thumbnail: thumbnail, title: title, description: description)
      puts "Finished generating thumbanil and title"
    rescue 
      false
    end
  end

  validates :url, presence: true
  validates :url, format: {with: URI.regexp}, if: 'url.present?'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy

  validates :title, length: {minimum: 3}, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def full_name
    return "#{first_name} #{last_name}"
  end

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @bookmark = Bookmark.find(params[:id])
    @topic = @bookmark.topic
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @bookmark
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @topic = Topic.find(params[:topic_id])
    @bookmark.topic = @topic
    @bookmark.user = current_user
    authorize @bookmark
    if @bookmark.save
      flash[:notice] = "bookmarks has been saved"
      redirect_to [@topic, @bookmark]
    else
      flash[:error] = "Error saving bookmark"
      render :new
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @topic = @bookmark.topic
    authorize @bookmark
    if @bookmark.update_attributes(bookmark_params)
      flash[:notice] = "bookmarks has been saved"
      redirect_to [@topic, @bookmark]
    else
      flash[:error] = "Error saving bookmark"
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @topic = @bookmark.topic
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "Bookmark has been deleted"
      # redirect_to @topic
    else 
      flash[:error] = "Error deleting topic"
      # render :show
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :title, :description)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    puts "INCOMING PARAMS HERE: #{params}"

    # You put the message-splitting and business
    # magic here.
    @user = User.find_by_email(params[:sender])
    @topic = @user.nil? ? nil : Topic.find_by_title(params[:subject])
    @url = params["body-plain"]

    if @user.nil?
      generated_password = Devise.friendly_token.first(8)
      @user = User.new(
        email: params[:sender],
        password: generated_password,
        password_confirmation: generated_password
      )
      @user.skip_confirmation_notification!
      @user.save
      RegistrationMailer.welcome(@user, @user.confirmation_token , generated_password).deliver_now
    end

    if @topic.nil?
      @topic = @user.topics.new(
        title: params[:subject]
      )
      @topic.save
    end

    @bookmark = @topic.bookmarks.build(url: @url)
    @bookmark.save

    # Assuming all went well.
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    authorize like
    if like.save
     flash[:notice] = "Bookmark has been added to liked bookmakrs"
     redirect_to @bookmark
    else
     flash[:error] = "Error adding bookmark to liked bookmarks"
     redirect_to @bookmark
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find_by(bookmark_id: @bookmark.id)

    authorize like
    if like.destroy
     flash[:notice] = "Bookamr has been removed from liked bookmarks"
     redirect_to @bookmark
    else
     flash[:error] = "Error removing bookmark form liked bookmarks"
     reidrect_to @bookmark
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.paginate(page: params[:page], per_page: 10)
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    authorize @topic
    if @topic.save
      flash[:notice] = "Topic has been created."
      redirect_to topics_path
    else
      flash[:error] = "Error saving your topic."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])

    authorize @topic
    if @topic.update_attributes(topic_params)
      flash[:notice] = "Topic has been updated"
      redirect_to topics_path
    else
      flash[:error] = "Error updating your topic"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    
    authorize @topic
    if @topic.destroy
      flash[:notice] = "Topic has been deleted"
      # redirect_to topics_path
    else 
      flash[:error] = "Error deleting topic"
      # render :show
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private 
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_bookmarks = current_user.bookmarks
    @liked_bookmarks = current_user.likes
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_css(controller)
    if  controller.class.to_s.downcase.exclude?('welcome')
      return "in-form"
    end
  end

  def add_btn_sm(controller)
    if controller.class.to_s.downcase.exclude?('bookmark')
      return 'btn-sm'
    end
  end

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group row has-danger'
    else
      content_tag :div, capture(&block), class: 'form-group row'
    end
  end
  def add_error_tag
    return "form-control-danger"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.erb
<%= content_tag :div, class:"col-lg-3 col-md-4 col-sm-12 text-xs-left", id:"bookmark-#{bookmark.id}" do %>
  <div class="card">
    <% if policy(bookmark).edit? %>
      <%= render partial: "bookmarks/function", locals:{bookmark: bookmark} %>
    <% end %>
    <div class="card-block">
      <h5 class="card-title"><%= link_to bookmark.title, [bookmark.topic, bookmark] %></h5>
      <h6 class="card-subtitle text-muted"><%= bookmark.topic.title %></h6>
    </div>
    <%= image_tag bookmark.thumbnail, size: "150x150",class:"card-img-top img-fluid center-block" %>
    <div class="card-block">
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
      <%= link_to "Link", bookmark.url, class: "btn btn-primary-outline btn-sm" %>
      <div><small class="text-muted"><%= "Added #{time_ago_in_words(bookmark.created_at)} ago" %></small></div>
    </div>
  </div>
<% end %>

app/views/bookmarks/_form.html.erb
<%= form_for [topic, bookmark], html: {class: "row"} do |f| %>
  <% if topic.errors.any? %>
  <div class="alert alert-danger text-xs-left">
    <h4><%= pluralize(@bookmark.errors.count, "error") %>.</h4>
    <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_group_tag(@bookmark.errors[:url]) do  %>
      <%= f.label :url, class: 'col-sm-2 col-md-4 form-control-label text-xs-left' %>
      <div class="col-sm-10 col-md-8">
        <%= f.text_field :url, autofocus: true, class: " col-sm-8 form-control #{add_error_tag if topic.errors.any?}", placeholder: "http://www.example.com" %>
      </div> 
  <% end %>   
  <%= form_group_tag(@bookmark.errors[:title]) do  %>
      <%= f.label :title, class: 'col-sm-2 col-md-4 form-control-label text-xs-left' %>
      <div class="col-sm-10 col-md-8">
        <%= f.text_field :title, autofocus: true, class: " col-sm-8 form-control #{add_error_tag if topic.errors.any?}", placeholder: "Enter Title(optional)" %> 
      </div> 
  <% end %> 
  <%= form_group_tag(@bookmark.errors[:description]) do  %>
      <%= f.label :description, class: 'col-sm-2 col-md-4 form-control-label text-xs-left' %>
      <div class="col-sm-10 col-md-8">
        <%= f.text_area :description, autofocus: true, class: " col-sm-8 form-control #{add_error_tag if topic.errors.any?}", placeholder: "Enter Description(optional)" %> 
      </div> 
  <% end %>           
  <div class="form-group row has-error">
    <div class="col-sm-4 col-sm-push-8 text-xs-right">
      <%= f.submit "Submit", class: 'btn btn-primary-outline btn-block' %>
    </div>
  </div>
<% end %>

app/views/bookmarks/_function.html.erb
<div class="row card-block pull-right">
  <div>
    <%= link_to [bookmark.topic, bookmark], html_options = { method: :delete, remote: true, "data-toggle":"tooltip", "data-placement": "top", title: "Remove Bookamrk", class: "btn-sm btn-danger-outline"}  do %>
      <span class="fa fa-times"></span>
    <% end %>
  </div>
  <div>
    <%= link_to edit_topic_bookmark_path(bookmark.topic, bookmark), html_options = {"data-toggle":"tooltip", "data-placement": "top", title: "Edit Bookmark", class: "btn-sm  btn-primary-outline"}  do %>
      <span class="fa fa-pencil"></span>
    <% end %>
  </div>
</div>

app/views/bookmarks/destroy.js.erb
<% if @bookmark.destroyed? %>
  flashMsg( '#bookmark-' +<%= @bookmark.id %>, ".bookmark-border" ,"<%= flash[:notice] %>", "success")
  $('#bookmark-' +<%= @bookmark.id %>).fadeOut(1000);
  <% flash.discard %>
<% else %>
  flashMsg("<%= flash[:error] %>", "error")
<% end %>

app/views/bookmarks/edit.html.erb
<h2>Edit: <%= @bookmark.title %></h2>
<%= render partial: "bookmarks/form", locals: {topic: @topic, bookmark: @bookmark} %>

app/views/bookmarks/new.html.erb
<h2>New Bookmark</h2>

<%= render partial: "bookmarks/form", locals: {topic: @topic, bookmark: @bookmark} %>

app/views/bookmarks/show.html.erb
<div class="row">
  <div class="row">
    <h2><%= @bookmark.title %></h2>
    <small><%= @bookmark.topic.title %></small>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-3 col-md-5 col-sm-12"><%= image_tag @bookmark.thumbnail, class: "card-img-top img-fluid" %></div>
  </div>
  <div class="row" style="margin-top: 10px;">
    <div><%= @bookmark.description %></div>
    <div class="pull-right"><%= link_to "Delete", [@topic, @bookmark], method: :delete, class: "btn btn-danger-outline d-btn" %></div>
    <%= render partial: 'likes/like', locals: { bookmark: @bookmark } %>
    <div class="pull-right"><%= link_to "Edit", edit_topic_bookmark_path(@topic, @bookmark), class: "btn btn-primary-outline e-btn" %></div>
    <div><%= link_to "Visit Link", @bookmark.url, class: "btn btn-primary-outline" %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmarks</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav id="topNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <ul class="nav navbar-nav pull-xs-right user-info">
          <% if current_user %>
            <li class="dropdown pull-right">
              <button href="#" data-toggle="dropdown" class="dropdown-toggle btn btn-sm btn-primary-outline"><span class="fa fa-user"></span></button>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Edit profile", edit_user_registration_path %>
                  </li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
            </li>
            <div class="pull-right">
              Hello <%= link_to current_user.email, current_user %>!
            </div>
          <% else %>
           <div class="pull-right">
               <%= link_to "Sign in", new_user_session_path %> or
               <%= link_to "Sign up", new_user_registration_path %>
           </div>
          <% end %>
        </ul>

        <button class="navbar-toggler hidden-md-up pull-left collapsed" type="button" data-toggle="collapse" data-target="#collapsingNavbar" aria-expanded="false">
            ☰
        </button>
        <a class="navbar-brand" href="#first"><span class="fa fa-bookmark"></span>Blocmarks</a>
        <div class="navbar-toggleable-sm collapse" id="collapsingNavbar" aria-expanded="false" style="height: 0px;">
          <ul class="nav navbar-nav">
            <li class="nav-item">
              <%= link_to "Home", root_path, html_options = {class: "nav-link"} %>
            </li>
            <li class="nav-item">
              <%= link_to "Topics", topics_path, html_options = {class: "nav-link"} %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, html_options = {class: "nav-link"} %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="inner-body">
      <div class="body-content <%= add_css(controller)%>">
        <div class="inner">
          <div class="<%= "text-xs-left" if controller.class.to_s.downcase.exclude?("welcome") %>">
            <% if flash[:notice] %>
              <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
              </div>
            <% elsif flash[:error] %>
              <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:error] %>
              </div>
            <% elsif flash[:alert] %>
              <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if policy(bookmark.likes.new).create? %>
  <div class="pull-right">
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark, like],  html_options = { method: :delete, "data-toggle":"tooltip", "data-placement": "top", title: "Unlike Bookmark",  class: "btn btn-danger-outline #{add_btn_sm(controller)}"} do %>
        <span class="fa fa-heart"></span>
      <% end %>
    <% else %>
      <%= link_to [bookmark, Like.new], html_options = { method: :post, "data-toggle":"tooltip", "data-placement": "top", title: "Like Bookmark",  class: "btn btn-primary-outline #{add_btn_sm(controller)}"} do %>
        <span class="fa fa-heart-o"></span>
      <% end %>
    <% end %>
  </div>  
<% end %>

app/views/topics/_bookmark.html.erb
<div class="col-lg-3 col-md-4 col-sm-12 text-xs-left">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title text-overflow"><%= link_to bookmark.title, [@topic, bookmark] %></h4>
      <h6 class="card-subtitle text-muted"><%= @topic.title %></h6>
    </div>
    <%= image_tag bookmark.thumbnail, size: "150x150",class:"card-img-top img-fluid center-block" %>
    <div class="card-block">
      <%= link_to "Link", bookmark.url, class: "btn btn-primary-outline btn-sm" %>
      <div><small class="text-muted"><%= "Added #{time_ago_in_words(bookmark.created_at)} ago" %></small></div>
    </div>
  </div>
</div>

app/views/topics/_form.html.erb
<%= form_for topic, html: {class: "row"} do |f| %>
  <% if topic.errors.any? %>
  <div class="alert alert-danger text-xs-left">
    <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
    <ul>
      <% topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_group_tag(topic.errors[:title]) do  %>
      <%= f.label :title, class: 'col-sm-2 col-md-4 form-control-label text-xs-left' %>
      <div class="col-sm-10 col-md-8">
        <%= f.text_field :title, autofocus: true, class: " col-sm-8 form-control #{add_error_tag if topic.errors.any?}", placeholder: "Enter name" %> 
      </div> 
  <% end %>         
  <div class="form-group row has-error">
    <div class="col-sm-4 col-sm-push-8 text-xs-right">
      <%= f.submit "Create", class: 'btn btn-primary-outline btn-block' %>
    </div>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<%= content_tag :div, class: 'row', id: "topic-#{topic.id}" do %>
  <div class="media text-xs-left">
    <div class="media-body">
      <div class="row">
        <% if policy(topic).destroy? %>
          <div class="pull-right">
            <%= link_to topic, html_options = { method: :delete, remote: true, "data-toggle":"tooltip", "data-placement": "top", title: "Remove Topic", class: "btn-sm btn-danger-outline t-btn"}  do %>
              <span class="fa fa-times"></span>
            <% end %>
          </div>
        <% end %>
        <% if policy(topic).update? %>
          <div class="pull-right">
            <%= link_to edit_topic_path(topic), html_options = {"data-toggle":"tooltip", "data-placement": "top", title: "Edit Topic", class: "btn-sm  btn-primary-outline"}  do %>
              <span class="fa fa-pencil"></span>
            <% end %>
          </div>
        <% end %>
        <h5 class="media-heading" style="margin-left: 15px;"><%= link_to "#{topic.title}", topic %><h5>
      </div>
      <div class="row bookmark-border">
        <%= render partial: "bookmarks/bookmark", collection: topic.bookmarks.limit(4).order("RANDOM()"), locals:{topic: topic} %>
      </div>
    </div>
  </div> 
<% end %>
<hr>

app/views/topics/destroy.js.erb
<% if @topic.destroyed? %>
  flashMsg( '#topic-' +<%= @topic.id %>, '#topic-' +<%= @topic.id %> ,"<%= flash[:notice] %>", "success")
  $('#topic-' +<%= @topic.id %>).next('hr').fadeOut(1000);
  $('#topic-' +<%= @topic.id %>).fadeOut(1000);
  <% flash.discard %>
<% else %>
  flashMsg("<%= flash[:error] %>", "error")
<% end %>

app/views/topics/edit.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1 text-xs-center">
    <div class="row text-xs-left">
      <h2>Sign up</h2>
    </div>
    <%= render partial: 'form', locals: {topic: @topic} %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <h2 class="pull-left">All topics</h2>
  <% if policy(Topic.new).create? %>  
    <div class="pull-right">
      <%= link_to new_topic_path, html_options = {"data-toggle":"tooltip", "data-placement": "top", title: "New Topic", class: "btn btn-primary-outline fn-btn"}  do %>
        <span class="fa fa-plus"></span>
      <% end %>
    </div>
  <% end %>
</div>

<%= render @topics%>

<%= will_paginate @topics %>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1 text-xs-center">
    <div class="row text-xs-left">
      <h2>Sign up</h2>
    </div>
    <%= render partial: 'form', locals: {topic: @topic} %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="row">
  <div class="row">
    <h2 class="pull-left"><%= @topic.title %></h2>
    <% if policy(Bookmark.new).create?  %>
      <div class="pull-right">
        <%= link_to new_topic_bookmark_path(@topic), html_options = {"data-toggle":"tooltip", "data-placement": "top", title: "New Bookmark", style: "margin-top: 0px", class: "btn btn-primary-outline fn-btn"}  do %>
          <span class="fa fa-plus"></span>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row bookmark-border">
    <%= render partial: "bookmarks/bookmark", collection: @bookmarks, locals:{topic: @topic} %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#user-bookmarks" role="tab">My Bookmarks</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#liked-bookmarks" role="tab">Liked Bookmarks</a>
    </li>
  </ul>
<br>
  <div class="tab-content">
    <div class="tab-pane active" id="user-bookmarks" role="tabpanel">
      <%= render @user_bookmarks %>
    </div>
    <div class="tab-pane" id="liked-bookmarks" role="tabpanel">
      <% @liked_bookmarks.each do |like| %>
        <%= render partial: "bookmarks/bookmark", locals: {bookmark: like.bookmark} %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h2>What's Blocmarks?</h2>
<h5 class="text-normal">A Social Bookmarking App With Email Integration</h5>
<h6 class="text-normal"> Email, Manage and Share Bookmarked URLs</h6>
<hr>
<%= link_to "Get Started", new_user_registration_path, html_options = {class: "btn btn-primary-outline btn-xl"} %>